version: "3.9"

services:
  db:
    image: mysql
    volumes:
      - ./data/db:/var/lib/mysql/data
    environment:
      - MYSQL_DB=cashapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
      - MYSQL_HOST=db

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DB=cashapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=0000
      - MYSQL_HOST=db
    depends_on:
      - db