build:
  stage: build
  script:
      - docker build -t http://docker.et3.co/internship.nadah:$CI_COMMIT_TAG -t http://docker.et3.co/internship.nadah:latest .
      - docker push http://docker.et3.co/internship.nadah
  only:
    - tags
test:
  stage: test
  script:
      - docker run --rm http://docker.et3.co/internship.nadah python http://manage.py test
  only:
    - tags
deploy:
  stage: deploy
  script:
      - kubectl apply -f ./k8s/postgres/persistent-volume.yml
      - kubectl apply -f ./k8s/postgres/persistent-volume-claim.yml
      - kubectl apply -f ./k8s/postgres/deployment.yml
      - kubectl apply -f ./k8s/postgres/service.yml
      - kubectl apply -f ./k8s/persistent-volume.yml
      - kubectl apply -f ./k8s/persistent-volume-claim.yml
      - kubectl delete --ignore-not-found -f ./k8s/deployment.yml
      - kubectl apply -f ./k8s/deployment.yml
      - kubectl apply -f ./k8s/service.yml
      - kubectl apply -f ./k8s/ingress.yml
  only:
    - tags