apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: internship
  creationTimestamp: null
  labels:
    name: nadah
  name: nadah-internship
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  selector:
    matchLabels:
      service: nadah-internship
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: nadah-internship
    spec:
      containers:
      - name: nadah-internship
        image: docker.et3.co/internship.nadah:latest
        command: ["sh"]
        args: ["runserver.sh"]
        env:
          - name: DEBUG
            value: "False"        
          - name: POSTGRES_USER
            value: postres
          - name: POSTGRES_ENGINE
            value: django.db.backends.postgresql_psycopg2
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_HOST
            value: postgres-internship-nadah
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_NAME
            value: postgres
        volumeMounts:
        - mountPath: /usr/src/app/data
          name: nadah-internship-volume-mount
        - mountPath: /usr/src/media
          name: nadah-media-internship-volume-mount
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nadah-internship-volume-mount
        persistentVolumeClaim:
          claimName: nadah-internship-pvc
      - name: nadah-media-internship-volume-mount
        persistentVolumeClaim:
          claimName: nadah-media-internship-pvc

