# Generated by Django 4.0.3 on 2022-09-02 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_current_credit_account_current_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('type', models.CharField(max_length=150)),
                ('receivant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivant', to='app.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='app.account')),
            ],
        ),
    ]
