apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: ese
  name: postgres-ese-communities-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-ese-communities-pv"
