apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: internship
  name: postgres-internship-nadah-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-internship-nadah-pv
  storageClassName: standard
