apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: internship
  name: postgres-internship-nadah-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres-internship-nadah-pv"
