apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ese
  name: postgres-ese-communities-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-ese-communities-pv
  storageClassName: standard
