apiVersion: v1
kind: Service
metadata:
  namespace: ese
  name: postgres-ese-communities
  labels:
    service: postgres-ese-communities
spec:
  selector:
    service: postgres-ese-communities
  type: ClusterIP
  ports:
  - port: 5432
