apiVersion: v1
kind: Service
metadata:
  namespace: internship
  name: postgres-internship-nadah
  labels:
    service: postgres-internship-nadah
spec:
  selector:
    service: postgres-internship-nadah
  type: ClusterIP
  ports:
  - port: 5432
